In [ ]:
import numpy as np


In [ ]:
list1=[10,20,30,40,50]
print(list1)
print(type(list1))

[10, 20, 30, 40, 50]
<class 'list'>


In [ ]:
arr=np.array(list1)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.array([12,13,14,15])
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
arr2=np.array([[10,20,30],[40,50,20],[70,80,40]])
print(arr2)

[[10 20 30]
 [40 50 20]
 [70 80 40]]


In [ ]:
arr3=np.array([[[10,30,56],[98,65,34],[65,42,43]],
 [[43,56,75,],[74,40,10],[82,45,67]],
  [[34,76,87],[92,46,87],[87,45,23]],
               [[25,67,90],[25,76,54],[63,90,70]],
               [[20,50,80],[94,80,23],[87,96,54]],
               [[92,90,75],[93,75,78],[93,56,86]],
               [[10,30,56],[98,65,34],[65,42,43]],
 [[43,56,75,],[74,40,10],[82,45,67]],
  [[34,76,87],[92,46,87],[87,45,23]],
                              [[25,67,90],[25,76,54],[63,90,70]]

               ])
print(arr3)

[[[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]

 [[20 50 80]
  [94 80 23]
  [87 96 54]]

 [[92 90 75]
  [93 75 78]
  [93 56 86]]

 [[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]]


In [ ]:
arr4=np.zeros((8),dtype=int)
print(arr4)

[0 0 0 0 0 0 0 0]


In [ ]:
arr5=np.zeros((3,4),dtype=int)
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
arr6=np.zeros((3,4,4),dtype=int)
print(arr6)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
arr7=np.zeros((2,4,4),dtype=int)
print(arr7)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
arr8=np.ones(5,dtype=int)
print(arr8)

[1 1 1 1 1]


In [ ]:
arr9=np.identity(5,dtype=int)
print(arr9)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
arr10=np.eye(10,dtype=int)
print(arr10)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [ ]:
arr11=np.tile(np.eye(3,4),(2,1,1))
print(arr11)

[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]


In [ ]:
arr12=np.arange(1,25,3)
print(arr12)

[ 1  4  7 10 13 16 19 22]


In [ ]:
arr13=np.linspace(1,100,5,dtype=int)
print(arr13)

[  1  25  50  75 100]


In [ ]:
arr14=np.copy(arr)
print(arr14)

[10 20 30 40 50]


In [ ]:
arr15=np.copy(arr3)
print(arr15)

[[[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]

 [[20 50 80]
  [94 80 23]
  [87 96 54]]

 [[92 90 75]
  [93 75 78]
  [93 56 86]]

 [[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]]


In [ ]:
print(arr15)
print(arr15.shape)

[[[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]

 [[20 50 80]
  [94 80 23]
  [87 96 54]]

 [[92 90 75]
  [93 75 78]
  [93 56 86]]

 [[10 30 56]
  [98 65 34]
  [65 42 43]]

 [[43 56 75]
  [74 40 10]
  [82 45 67]]

 [[34 76 87]
  [92 46 87]
  [87 45 23]]

 [[25 67 90]
  [25 76 54]
  [63 90 70]]]
(10, 3, 3)


In [ ]:
print(arr2)
print(arr2.ndim)

[[10 20 30]
 [40 50 20]
 [70 80 40]]
2


In [ ]:
print(arr2)
print(arr2.size)

[[10 20 30]
 [40 50 20]
 [70 80 40]]
9


In [ ]:
print(arr2)
print(arr2.itemsize,"bytes")

[[10 20 30]
 [40 50 20]
 [70 80 40]]
8 bytes


In [ ]:
arr16=arr2.astype(float)
print(arr16)

[[10. 20. 30.]
 [40. 50. 20.]
 [70. 80. 40.]]


In [ ]:
#Q.1 - Create a NumPy array from [10,20,30,40,50]. Display its shape, size, and data type. Do the same for 2d and 3d.
arr17=np.array([10,20,30,40,50])
arr18=np.array([[23,34,45],[86,43,56]])
arr19=np.array([[[23,65,76],[78,8,65]],[[76,74,26],[51,38,80]]])
print(arr17.shape)
print(arr17.size)
print(arr17.dtype)
print(arr18.shape)
print(arr18.size)
print(arr18.dtype)
print(arr19.shape)
print(arr19.size)
print(arr19.dtype)

(5,)
5
int64
(2, 3)
6
int64
(2, 2, 3)
12
int64


In [ ]:
#Q.2 - Create a 3*4 array containing numbers from 1 to 12
arr20=np.arange(1,13).reshape(3,4)
print(arr20)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Q.3 - Create an array of zeros,an array of ones and an identity matrix
arr21=np.zeros((3,4),dtype=int)
arr22=np.ones((3,4),dtype=int)
arr23=np.eye((5),dtype=int)

print(arr21,"\n")
print(arr22,"\n")
print(arr23)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#Q.4 Generate all even numbers between 10 and 50 using np.arange
arr24=np.arange(10,51,2)
print(arr24)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Q.5 Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
arr25=np.linspace(0,1,10)
print(arr25)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Q.6 Given two Numpy arrays,perform element-wise addition,subtraction and multipication and division
arr26=np.array(1,2,3,4,5)
arr26=np.array(10,20,30,40,50)
print("add",)

In [ ]:
#Q.7 Calculate the square and cube of every element in a NumPy array

In [ ]:
#Q.8 Increase every element of an array by 15%

In [ ]:
#Q.9 Given two arrays, find their element-wise maximum and minimum